#!/bin/bash

dir="$(dirname "$0")"

DEPS="$dir/data/dependencies-opensuse.list"

DEPS="$dir/data/dependencies-archlinux.list"

DEPSUBUNTU="$dir/data/dependencies-ubuntu.list"


# Dependency Check
function check {
    case `lsb_release -i` in
	    Ubuntu)
    show_info "Checking dependencies..."
    for package in $(cat $DEPSUBUNTU)
    do 
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $package|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        show_info "This script makes use of '$package' and it is not present on your system."
        show_question 'Would you like to install it to continue? (Y)es, (N)o : ' && read REPLY
        echo ''
        case $REPLY in
        # Positive action
        [Yy]* ) 
            show_warning 'Requires root privileges'
            sudo apt-get --force-yes --yes install $package
            show_success 'Done. Proceeding.'
            main
            ;;
        # Negative action
        [Nn]* )
            show_info "Exiting.."
            clear && exit 99
            ;;
        # Error
        * )
            clear && show_error '\aSorry, try again.' && check
            ;;
        esac
    else
        show_info "'$package' is installed. Proceeding"
    fi
    done
	        ;;
	    Fedora)
	        ;;
	    archlinux)
	        ;;
	    openSUSE)
	        ;;
	    *)
	        show_error "No packages available to download that matches your system." && thirdparty
	        ;;
	esac	
}
