#!/bin/bash

# Erasing all
function erase-all {
    show_info 'Erasing boot...'
    fastboot erase boot
    # Reboot bootloader
    show_warning 'Devices rebooting'
    fastboot reboot-bootloader
    # Timeout
    sleep 5
    show_info 'Erasing cache...'
    fastboot erase cache
    # Reboot bootloader
    show_warning 'Devices rebooting'
    fastboot reboot-bootloader
    # Timeout
    sleep 5
    show_info 'Erasing radio...'
    fastboot erase radio
    # Reboot bootloader
    show_warning 'Devices rebooting'
    fastboot reboot-bootloader
    # Timeout
    sleep 5
    show_info 'Erasing recovery...'
    fastboot erase recovery
    # Reboot bootloader
    show_warning 'Devices rebooting'
    fastboot reboot-bootloader
    # Timeout
    sleep 5
    show_info 'Erasing system...'
    fastboot erase system
    # Reboot bootloader
    show_warning 'Devices rebooting'
    fastboot reboot-bootloader
    # Timeout
    sleep 5
    show_info 'Erasing userdata...'
    fastboot erase userdata
    # Reboot bootloader
    show_warning 'Devices rebooting'
    fastboot reboot-bootloader
    # Timeout
    sleep 5
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Erasure performed." 8 78
    erase
}

# Erase boot
function erase-boot {
    show_info 'Erasing boot...'
    fastboot erase boot
    # Reboot bootloader
    show_warning 'Devices rebooting'
    fastboot reboot-bootloader
    # Timeout
    sleep 5
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Erasure performed." 8 78
    erase
}

# Erase cache
function erase-cache {
    show_info 'Erasing cache...'
    fastboot erase cache
    # Reboot bootloader
    show_warning 'Devices rebooting'
    fastboot reboot-bootloader
    # Timeout
    sleep 5
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Erasure performed." 8 78
    erase
}

# Erase radio
function erase-radio {
    show_info 'Erasing radio...'
    fastboot erase radio
    # Reboot bootloader
    show_warning 'Devices rebooting'
    fastboot reboot-bootloader
    # Timeout
    sleep 5
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Erasure performed." 8 78
    erase
}

# Erase recovery
function erase-recovery {
    show_info 'Erasing recovery...'
    fastboot erase recovery
    # Reboot bootloader
    show_warning 'Devices rebooting'
    fastboot reboot-bootloader
    # Timeout
    sleep 5
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Erasure performed." 8 78
  erase
}

# Erase system
function erase-system {
  show_info 'Erasing system...'
  fastboot erase system
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Erasure performed." 8 78
  erase
}

# Erase userdata
function erase-userdata {
 show_info 'Erasing user data...'
 fastboot erase userdata
 # Reboot bootloader
 show_warning 'Devices rebooting'
 fastboot reboot-bootloader
 # Timeout
 sleep 5
 # Done
 show_success 'Done.'
 whiptail --title "Finished" --msgbox "Erasure performed." 8 78
 erase
}

# Erase sections
function erase {
    eval `resize`
    ERASE=$(whiptail \
        --notags \
        --title "Erase sections" \
        --menu "\nWhat would you like to do?" \
        --ok-button "Erase" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        erase-all 'Erase all' \
        erase-boot 'Erase boot section' \
        erase-cache 'Erase cache section' \
        erase-radio 'Erase radio' \
        erase-recovery 'Erase recovery section' \
        erase-system 'Erase system' \
        erase-userdata 'Erase userdata' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $ERASE
    else
        clear && main
    fi
}
