#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/images-data/images-angler
source $dir/functions/images-data/images-bullhead
source $dir/functions/images-data/images-fugu
source $dir/functions/images-data/images-hammerhead
source $dir/functions/images-data/images-mantaray
source $dir/functions/images-data/images-nakasi
source $dir/functions/images-data/images-nakasig
source $dir/functions/images-data/images-occam
source $dir/functions/images-data/images-razor
source $dir/functions/images-data/images-razorg
source $dir/functions/images-data/images-ryu
source $dir/functions/images-data/images-shamu
source $dir/functions/images-data/images-takju
source $dir/functions/images-data/images-volantis
source $dir/functions/images-data/images-volantisg
source $dir/functions/images-data/images-yakju

# Install Factory Images
function images {
    eval `resize`
    IMAGES=$(whiptail \
        --notags \
        --title "Install Factory Images" \
        --menu "\nWhich device you want to flash?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        images-ryu 'Pixel C' \
        images-angler 'Nexus 6P' \
        images-bullhead 'Nexus 5X' \
        images-shamu 'Nexus 6' \
        images-fugu 'Nexus Player' \
        images-volantisg 'Nexus 9 (LTE)' \
        images-volantis 'Nexus 9 (Wi-Fi)' \
        images-hammerhead 'Nexus 5' \
        images-razor 'Nexus 7 [2013] (Wi-Fi)' \
        images-razorg 'Nexus 7 [2013] (Mobile)' \
        images-mantaray 'Nexus 10' \
        images-occam 'Nexus 4' \
        images-nakasi 'Nexus 7 (Wi-Fi)' \
        images-nakasig 'Nexus 7 (Mobile)' \
        images-takju 'Galaxy Nexus maguro (with Google Wallet)' \
        images-yakju 'Galaxy Nexus maguro' \
        3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $IMAGES
  else
    clear && main
  fi
}
