#!/bin/bash

dir="$(dirname "$0")"

. $dir/functions/backup
. $dir/functions/developer-preview
. $dir/functions/gapps
. $dir/functions/root

# Other tools
function tools {
eval `resize`
TOOLS=$(whiptail \
--notags \
--title "Other tools" \
--menu "\nWhat recovery would you like to install?" \
--ok-button "Install" \
--cancel-button "Go Back" \
$LINES $COLUMNS $(( $LINES - 12 )) \
'backup'                  'Backup/Restore' \
'developer-preview'       'Install Developer Preview Images' \
'gapps'                   '' \
'root'                    '' \
3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $TOOLS
  else
    clear && main
  fi
}
