#!/bin/bash

# Search devices
function search {
  show_info 'Start the device in fastboot mode...'
  show_warning 'Devices rebooting'
  adb reboot bootloader
  show_info 'Verify that your phone is in fastboot mode...'
  fastboot devices
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "The device is connected." 8 78
  main
}
