#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Nexus 5
function images-hammerhead {
eval `resize`
exitstatus=$?
if [ $exitstatus = 0 ]; then
    status="0"
    while [ "$status" -eq 0 ]
    do

        VERSION=$(whiptail \
        --title "Nexus 5" --radiolist \
        "For what device you want to flash the recovery?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        "KRT16M"         "KitKat 4.4" OFF \
        "KTU84P"         "KitKat 4.4.4" OFF \
        "LRX21O"         "Lollipop 5.0" OFF \
        "LMY48M"         "Lollipop 5.1.1" OFF \
        "MRA58N"         "Marshmallow 6.0.0" OFF \
        "MMB29Q"         "Marshmallow 6.0.1" ON \

        3>&1 1>&2 2>&3)

        # Change to lower case and remove spaces.
        case "${VERSION}" in
            KRT16M)
              # Download
              show_info 'Download Factory Images...'
              curl -O https://dl.google.com/dl/android/aosp/hammerhead-krt16m-factory-bd9c39de.tgz
              show_info 'Extraction Factory Images...'
            	tar zxf hammerhead*.tgz
              show_info 'Install Factory Images...'
              show_warning ' '
              cd hammerhead-krt16m
              ./flash-all.sh
              # Done
              show_success 'Done.'
              whiptail --title "Finished" --msgbox "Installation complete." 8 78
              status=1
              images
            ;;
            KTU84P)
              # Download
              show_info 'Download ...'
              curl -O https://dl.google.com/dl/android/aosp/hammerhead-ktu84p-factory-35ea0277.tgz
              show_info 'Extraction f...'
            	tar zxf hammerhead*.tgz
              cd hammerhead-ktu84p
              ./flash-all.sh
              # Done
              show_success 'Done.'
              whiptail --title "Finished" --msgbox "Installation complete." 8 78
              status=1
              images
            ;;
            LRX21O)
              # Download
              show_info 'Download ...'
              curl -O https://dl.google.com/dl/android/aosp/hammerhead-lrx21o-factory-01315e08.tgz
              show_info 'Extraction f...'
              tar zxf hammerhead*.tgz
              cd hammerhead-lrx21o
              ./flash-all.sh
              # Done
              show_success 'Done.'
              whiptail --title "Finished" --msgbox "Installation complete." 8 78
              status=1
              images
            ;;
            LMY48M)
              # Download
              show_info 'Download ...'
              curl -O https://dl.google.com/dl/android/aosp/hammerhead-lmy48m-factory-bf3c82fd.tgz
              show_info 'Extraction f...'
              tar zxf hammerhead*.tgz
              cd hammerhead-lmy48m
              ./flash-all.sh
              # Done
              show_success 'Done.'
              whiptail --title "Finished" --msgbox "Installation complete." 8 78
              status=1
              images
            ;;
            MRA58N)
              # Download
              show_info 'Download ...'
              curl -O https://dl.google.com/dl/android/aosp/hammerhead-mra58n-factory-aeca4139.tgz
              show_info 'Extraction f...'
              tar zxf hammerhead*.tgz
              cd hammerhead-mra58n
              ./flash-all.sh
              # Done
              show_success 'Done.'
              whiptail --title "Finished" --msgbox "Installation complete." 8 78
              status=1
              images
            ;;
            MMB29Q)
              # Download
              show_info 'Download ...'
              curl -O https://dl.google.com/dl/android/aosp/hammerhead-mmb29q-factory-6356d31e.tgz
              show_info 'Extraction f...'
              tar zxf hammerhead*.tgz
              show_info '...'
              cd hammerhead-mmb29q
              ./flash-all.sh
              # Done
              show_success 'Done.'
              whiptail --title "Finished" --msgbox "Installation complete." 8 78
              status=1
              images
            ;;
            *) status=1
              images
            ;;
        esac
        exitstatus1=$status1
    done
else
    clear && images
fi
}
