#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function fugu-LRX21V {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/fugu-lrx21v-factory-64050f47.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf fugu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd fugu-lrx21v
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function fugu-LMY48N {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/fugu-lmy48n-factory-3b9d8638.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf fugu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd fugu-lmy48n
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function fugu-MRA58N {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/fugu-mra58n-factory-8517d819.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf fugu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd fugu-mra58n
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function fugu-MMB29V {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/fugu-mmb29v-factory-2db4c688.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf fugu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd fugu-mmb29v
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

# Nexus Player
function images-fugu {
  eval `resize`
  NEXUSPLAY=$(whiptail \
      --notags \
      --title "Nexus Player" \
      --menu "\nFor what device you want to flash the recovery?" \
      --ok-button "Install" \
      --cancel-button "Go Back" \
      $LINES $COLUMNS $(( $LINES - 12 )) \
      "fugu-LRX21V"         "Lollipop 5.0" \
      "fugu-LMY48N"         "Lollipop 5.1.1" \
      "fugu-MRA58N"         "Marshmallow 6.0.0" \
      "fugu-MMB29V"         "Marshmallow 6.0.1" \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $NEXUSPLAY
    else
        clear && main
    fi
}
