#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function ryu-MXB48T {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/ryu-mxb48t-factory-43820b34.tgz
  show_info 'Extraction Factory Images...'
  tar zxf ryu*.tgz
  show_info 'Install Factory Images...'
  show_warning ' '
  cd ryu-mxb48t
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

# Pixel C
function images-ryu {
  eval `resize`
  NEXUS5X=$(whiptail \
      --notags \
      --title "Pixel C" \
      --menu "\nFor what device you want to flash the recovery?" \
      --ok-button "Install" \
      --cancel-button "Go Back" \
      $LINES $COLUMNS $(( $LINES - 12 )) \
      "ryu-MXB48T"         "Marshmallow 6.0.1" \
      3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $PIXELC
    else
        clear && main
    fi
}
