#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function bullhead-dp1 {
  # Download
  show_info 'Download ...'
  curl -O http://storage.googleapis.com/androiddevelopers/shareables/preview/bullhead-npc56w-preview-d86c7559.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf bullhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd bullhead-npc56w
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  developer-preview
}

# Nexus 5X
function developer-preview-bullhead {
    eval `resize`
    NEXUS5X=$(whiptail \
        --notags \
        --title "Nexus 5X" \
        --menu "\nFor what device you want to flash the recovery?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        "bullhead-dp1"         "Developer Preview 1" \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $NEXUS5X
    else
        clear && main
    fi
}
