#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function shamu-dp1 {
  # Download
  show_info 'Download Factory Images...'
  curl -O http://storage.googleapis.com/androiddevelopers/shareables/preview/shamu-npc56p-preview-54b13c67.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf shamu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd shamu-npc56w
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function shamu-dp2 {
  # Download
  show_info 'Download Factory Images...'
  curl -O http://storage.googleapis.com/androiddevelopers/shareables/preview/shamu-npc91k-factory-7c9936dc.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf shamu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd shamu-npc91k
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

# Nexus 6
function developer-preview-shamu {
  eval `resize`
  NEXUS6=$(whiptail \
      --notags \
      --title "Nexus 6" \
      --menu "\nWhat is the firmware version you want to install?" \
      --ok-button "Install" \
      --cancel-button "Go Back" \
      $LINES $COLUMNS $(( $LINES - 12 )) \
      "shamu-dp1"         "Developer Preview 1" \
      "shamu-dp2"         "Developer Preview 2" \
      3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $NEXUS6
    else
        clear && main
    fi
}
