#!/bin/bash

function razor-JSS15R {
JSS15R="razor-jss15r-factory-ec2d4f76.tgz"
  if [ -f "$JSS15R" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor-jss15r*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-jss15r
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-jss15r*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/razor-jss15r-factory-ec2d4f76.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor-jss15r*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-jss15r
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-jss15r*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function razor-KRT16S {
KRT16S="razor-krt16s-factory-7235eb0d.tgz"
  if [ -f "$KRT16S" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-krt16s
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/razor-krt16s-factory-7235eb0d.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-krt16s
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function razor-KTU84P {
KTU84P="razor-ktu84p-factory-b1b2c0da.tgz"
  if [ -f "$KTU84P" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-ktu84p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/razor-ktu84p-factory-b1b2c0da.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-ktu84p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function razor-LRX21P {
LRX21P="razor-lrx21p-factory-ba55c6ab.tgz"
  if [ -f "$LRX21P" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-lrx21p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/razor-lrx21p-factory-ba55c6ab.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-lrx21p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function razor-LRX22G {
LRX22G="razor-lrx22g-factory-bff2093e.tgz"
  if [ -f "$LRX22G" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor-lrx22g*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-lrx22g
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-lrx22g*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/razor-lrx22g-factory-bff2093e.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor-lrx22g*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-lrx22g
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-lrx22g*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function razor-LMY48T {
LMY48T="razor-lmy48t-factory-b6a844f2.tgz"
  if [ -f "$LMY48T" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor-lmy48t*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-lmy48t
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-lmy48t*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/razor-lmy48t-factory-b6a844f2.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razor-lmy48t*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razor-lmy48t
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razor-lmy48t*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function razorg-MRA59B {
MRA59B="razorg-mra59b-factory-088505a6.tgz"
  if [ -f "$MRA59B" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razorg-mra59b*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razorg-mra59b
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razorg-mra59b*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/razorg-mra59b-factory-088505a6.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razorg-mra59b*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razorg-mra59b
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razorg-mra59b*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function razorg-MOB30X {
MOB30X="razorg-mob30x-factory-10b7ca08.zip"
  if [ -f "$MOB30X" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razorg-mob30x*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razorg-mob30x
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razorg-mob30x*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/razorg-mob30x-factory-10b7ca08.zip
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf razorg-mob30x*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd razorg-mob30x
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf razorg-mob30x*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus 7
function images-razorg {
  eval `resize`
  NEXUS7M=$(whiptail \
    --notags \
    --title 'Nexus 7 [2013] (Mobile)' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    razorg-JSS15R 'Jelly Bean 4.3' \
    razorg-KRT16S 'KitKat 4.4' \
    razorg-KTU84P 'KitKat 4.4.4' \
    razorg-LRX21P 'Lollipop 5.0' \
    razorg-LRX22G 'Lollipop 5.0.2' \
    razorg-LMY48T 'Lollipop 5.1.1' \
    razorg-MRA59B 'Marshmallow 6.0' \
    razorg-MOB30X 'Marshmallow 6.0.1' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUS7M
  else
    clear && main
  fi
}
