#!/bin/bash

function fugu-LRX21V {
LRX21V="fugu-lrx21v-factory-2f283d96.zip"
  if [ -f "$LRX21V" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip fugu-lrx21v*.zip
    # Install
    show_info 'Install Factory Images...'
    cd fugu-lrx21v
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-lrx21v*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-lrx21v-factory-2f283d96.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip fugu-lrx21v*.zip
    # Install
    show_info 'Install Factory Images...'
    cd fugu-lrx21v
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-lrx21v*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function fugu-LMY48N {
LMY48N="fugu-lmy48n-factory-80ab3689.zip"
  if [ -f "$LMY48N" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip fugu-lmy48n*.zip
    # Install
    show_info 'Install Factory Images...'
    cd fugu-lmy48n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-lmy48n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-lmy48n-factory-80ab3689.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip fugu-lmy48n*.zip
    # Install
    show_info 'Install Factory Images...'
    cd fugu-lmy48n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-lmy48n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function fugu-MRA58N {
MRA58N="fugu-mra58n-factory-3b5bccdc.zip"
  if [ -f "$MRA58N" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip fugu-mra58n*.zip
    # Install
    show_info 'Install Factory Images...'
    cd fugu-mra58n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-mra58n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-mra58n-factory-3b5bccdc.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip fugu-mra58n*.zip
    # Install
    show_info 'Install Factory Images...'
    cd fugu-mra58n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-mra58n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function fugu-MOB30W {
MOB30W="fugu-mob30w-factory-a9242814.zip"
  if [ -f "$MOB30W" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip fugu-mob30w*.zip
    # Install
    show_info 'Install Factory Images...'
    cd fugu-mob30w
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-mob30w*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-mob30w-factory-a9242814.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip fugu-mob30w*.zip
    # Install
    show_info 'Install Factory Images...'
    cd fugu-mob30w
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-mob30w*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function fugu-NRD90R {
NRD90R="fugu-nrd90r-factory-663a9f79.zip"
  if [ -f "$NRD90R" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip fugu-nrd90r*.zip
    # Install
    show_info 'Install Factory Images...'
    cd fugu-nrd90r
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-nrd90r*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-nrd90r-factory-663a9f79.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip fugu-nrd90r*.zip
    # Install
    show_info 'Install Factory Images...'
    cd fugu-nrd90r
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-nrd90r*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus Player
function images-fugu {
  eval `resize`
  NEXUSPLAY=$(whiptail \
    --notags \
    --title 'Nexus Player' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    fugu-LRX21V 'Lollipop 5.0' \
    fugu-LMY48N 'Lollipop 5.1.1' \
    fugu-MRA58N 'Marshmallow 6.0' \
    fugu-MOB30W 'Marshmallow 6.0.1' \
    fugu-NRD90R 'Nougat 7.0' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUSPLAY
  else
    clear && main
  fi
}
