#!/bin/bash

function bullhead-MDB08M {
MDB08M="bullhead-mdb08m-factory-9f8fb666.zip"
  if [ -f "$MDB08M" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip bullhead-mdb08m*.zip
    # Install
    show_info 'Install Factory Images...'
    cd bullhead-mdb08m
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf bullhead-mdb08m*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/bullhead-mdb08m-factory-9f8fb666.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip bullhead-mdb08m*.zip
    # Install
    show_info 'Install Factory Images...'
    cd bullhead-mdb08m
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf bullhead-mdb08m*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function bullhead-MTC20K {
MTC20K="bullhead-mtc20k-factory-4a950470.zip"
  if [ -f "$MTC20K" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip bullhead-mtc20k*.zip
    # Install
    show_info 'Install Factory Images...'
    cd bullhead-mtc20k
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf bullhead-mtc20k*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download ...'
    wget https://dl.google.com/dl/android/aosp/bullhead-mtc20k-factory-4a950470.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip bullhead-mtc20k*.zip
    # Install
    show_info 'Install Factory Images...'
    cd bullhead-mtc20k
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf bullhead-mtc20k*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function bullhead-NRD90S {
NRD90S="bullhead-nrd90s-factory-d6bf1f56.zip"
  if [ -f "$NRD90S" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip bullhead-nrd90s*.zip
    # Install
    show_info 'Install Factory Images...'
    cd bullhead-nrd90s
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf bullhead-nrd90s*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download ...'
    wget https://dl.google.com/dl/android/aosp/bullhead-nrd90s-factory-d6bf1f56.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip bullhead-nrd90s*.zip
    # Install
    show_info 'Install Factory Images...'
    cd bullhead-nrd90s
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf bullhead-nrd90s*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus 5X
function images-bullhead {
  eval `resize`
  NEXUS5X=$(whiptail \
    --notags \
    --title 'Nexus 5X' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    bullhead-MDB08M 'Marshmallow 6.0' \
    bullhead-MTC20K 'Marshmallow 6.0.1' \
    bullhead-NRD90S 'Nougat 7.0' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUS5X
  else
    clear && main
  fi
}
