#!/bin/bash

function mantaray-JDQ39 {
JDQ39="mantaray-jdq39-factory-d79f489e.tgz"
  if [ -f "$JDQ39" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf mantaray-jdq39*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd mantaray-jdq39
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf mantaray-jdq39*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/mantaray-jdq39-factory-d79f489e.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf mantaray-jdq39*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd mantaray-jdq39
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf mantaray-jdq39*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function mantaray-JWR66Y {
JWR66Y="mantaray-jwr66y-factory-3d8252dd.tgz"
  if [ -f "$JWR66Y" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf mantaray-jwr66y*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd mantaray-jwr66y
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf mantaray-jwr66y*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/mantaray-jwr66y-factory-3d8252dd.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-jwr66y*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-jwr66y
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-jwr66y*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function mantaray-KRT16S {
KRT16S="mantaray-krt16s-factory-94413961.tgz"
  if [ -f "$KRT16S" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf mantaray-krt16s*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd mantaray-krt16s
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf mantaray-krt16s*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/mantaray-krt16s-factory-94413961.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf mantaray-krt16s*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd mantaray-krt16s
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf mantaray-krt16s*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function mantaray-KTU84P {
KTU84P="mantaray-ktu84p-factory-74e52998.tgz"
  if [ -f "$KTU84P" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf mantaray-ktu84p*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd mantaray-ktu84p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf mantaray-ktu84p*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/mantaray-ktu84p-factory-74e52998.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-ktu84p*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-ktu84p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-ktu84p*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function mantaray-LRX21P {
LRX21P="mantaray-lrx21p-factory-ad2499ea.tgz"
  if [ -f "$LRX21P" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf mantaray-lrx21p*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd mantaray-lrx21p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf mantaray-lrx21p*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/mantaray-lrx21p-factory-ad2499ea.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf mantaray-lrx21p*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd mantaray-lrx21p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf mantaray-lrx21p*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function mantaray-LMY49J {
LMY49J="mantaray-lmy49j-factory-7887b439.tgz"
  if [ -f "$LMY49J" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-lmy49j*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-lmy49j
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-lmy49j*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/mantaray-lmy49j-factory-7887b439.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf mantaray-lmy49j*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd mantaray-lmy49j
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf mantaray-lmy49j*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus 10
function images-mantaray {
  eval `resize`
  NEXUS10=$(whiptail \
    --notags \
    --title 'Nexus 10' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    mantaray-JDQ39 'Jelly Bean 4.2.2' \
    mantaray-JWR66Y 'Jelly Bean 4.3' \
    mantaray-KRT16S 'KitKat 4.4' \
    mantaray-KTU84P 'KitKat 4.4.4' \
    mantaray-LRX21PLRX21P 'Lollipop 5.0' \
    mantaray-LMY49J 'Lollipop 5.1.1' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUS10
  else
    clear && main
  fi
}
