#!/bin/bash

function hammerhead-KRT16M {
KRT16M="hammerhead-krt16m-factory-bd9c39de.zip"
  if [ -f "$KRT16M" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-krt16m*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-krt16m
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-krt16m*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/hammerhead-krt16m-factory-bd9c39de.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-krt16m*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-krt16m
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-krt16m*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function hammerhead-KTU84P {
KTU84P="hammerhead-ktu84p-factory-35ea0277.zip"
  if [ -f "$KTU84P" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-ktu84p*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-ktu84p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-ktu84p*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/hammerhead-ktu84p-factory-35ea0277.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-ktu84p*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-ktu84p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-ktu84p*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function hammerhead-LRX21O {
LRX21O="hammerhead-lrx21o-factory-01315e08.zip"
  if [ -f "$LRX21O" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-lrx21o*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-lrx21o
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-lrx21o*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/hammerhead-lrx21o-factory-01315e08.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-lrx21o*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-lrx21o
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-lrx21o*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function hammerhead-LMY48M {
LMY48M="hammerhead-lmy48m-factory-bf3c82fd.zip"
  if [ -f "$LMY48M" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-lmy48m*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-lmy48m
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-lmy48m*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/hammerhead-lmy48m-factory-bf3c82fd.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-lmy48m*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-lmy48m
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-lmy48m*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function hammerhead-MRA58N {
MRA58N="hammerhead-mra58n-factory-30da525d.zip"
  if [ -f "$MRA58N" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-mra58n*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-mra58n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-mra58n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/hammerhead-mra58n-factory-30da525d.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-mra58n*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-mra58n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-mra58n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function hammerhead-MOB31E {
MOB31E="hammerhead-mob31e-factory-90504514.zip"
  if [ -f "$MOB31E" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-mob31e*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-mob31e
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-mob31e*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/hammerhead-mob31e-factory-90504514.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip hammerhead-mob31e*.zip
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-mob31e
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead-mob31e*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus 5
function images-hammerhead {
  eval `resize`
  NEXUS5=$(whiptail \
    --notags \
    --title 'Nexus 5' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    hammerhead-KRT16M 'KitKat 4.4' \
    hammerhead-KTU84P 'KitKat 4.4.4' \
    hammerhead-LRX21O 'Lollipop 5.0' \
    hammerhead-LMY48M 'Lollipop 5.1.1' \
    hammerhead-MRA58N 'Marshmallow 6.0' \
    hammerhead-MOB31E 'Marshmallow 6.0.1' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUS5
  else
    clear && main
  fi
}
