#!/bin/bash

function angler-MMB29N {
MMB29N="angler-mmb29n-factory-b1463752.tgz"
  if [ -f "$MMB29N" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf angler-mmb29n*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd angler-mmb29n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf angler-mmb29n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/angler-mmb29n-factory-b1463752.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf angler-mmb29n*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd angler-mmb29n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf angler-mmb29n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function angler-MTC19X {
MTC19X="angler-mtc19x-factory-83a34810.tgz"
  if [ -f "$MTC19X" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf angler-mhc19q*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd angler-mhc19q
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf angler-mhc19q*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/angler-mtc19x-factory-83a34810.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf angler-mhc19q*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd angler-mhc19q
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf angler-mhc19q*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus 6P
function images-angler {
  eval `resize`
  NEXUS6P=$(whiptail \
    --notags \
    --title 'Nexus 6P' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    angler-MMB29N 'Marshmallow 6.0' \
    angler-MTC19X 'Marshmallow 6.0.1' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUS6P
  else
    clear && main
  fi
}
