#!/bin/bash

function angler-MMB29N {
MMB29N="angler-mmb29n-factory-63f8243f.zip"
  if [ -f "$MMB29N" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip angler-mmb29n*.zip
    # Install
    show_info 'Install Factory Images...'
    cd angler-mmb29n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf angler-mmb29n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/angler-mmb29n-factory-63f8243f.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip angler-mmb29n*.zip
    # Install
    show_info 'Install Factory Images...'
    cd angler-mmb29n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf angler-mmb29n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function angler-MTC20L {
MTC20L="angler-mtc20l-factory-a74ad54f.zip"
  if [ -f "$MTC20L" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    unzip angler-mtc20l*.zip
    # Install
    show_info 'Install Factory Images...'
    cd angler-mtc20l
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf angler-mtc20l*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/angler-mtc20l-factory-a74ad54f.zip
    # Extract
    show_info 'Extraction Factory Images...'
    unzip angler-mtc20l*.zip
    # Install
    show_info 'Install Factory Images...'
    cd angler-mtc20l
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf angler-mtc20l*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus 6P
function images-angler {
  eval `resize`
  NEXUS6P=$(whiptail \
    --notags \
    --title 'Nexus 6P' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    angler-MMB29N 'Marshmallow 6.0' \
    angler-MTC20L 'Marshmallow 6.0.1' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUS6P
  else
    clear && main
  fi
}
