#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/images-data/images-angler
source $dir/functions/images-data/images-bullhead
source $dir/functions/images-data/images-fugu
source $dir/functions/images-data/images-hammerhead
source $dir/functions/images-data/images-mantaray
source $dir/functions/images-data/images-nakasi
source $dir/functions/images-data/images-nakasig
source $dir/functions/images-data/images-occam
source $dir/functions/images-data/images-razor
source $dir/functions/images-data/images-razorg
source $dir/functions/images-data/images-ryu
source $dir/functions/images-data/images-shamu
source $dir/functions/images-data/images-takju
source $dir/functions/images-data/images-volantis
source $dir/functions/images-data/images-volantisg
source $dir/functions/images-data/images-yakju

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Install Factory Images
function images {
    eval `resize`
    IMAGES=$(whiptail \
        --notags \
        --title "Install Factory Images" \
        --menu "\nWhich device you want to flash?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'ryu'            'Pixel C' \
        'angler'         'Nexus 6P' \
        'bullhead'       'Nexus 5X' \
        'shamu'          'Nexus 6' \
        'fugu'           'Nexus Player' \
        'volantisg'      'Nexus 9 (LTE)' \
        'volantis'       'Nexus 9 (Wi-Fi)' \
        'hammerhead'     'Nexus 5' \
        'razor'          'Nexus 7 [2013] (Wi-Fi)' \
        'razorg'         'Nexus 7 [2013] (Mobile)' \
        'mantaray'       'Nexus 10' \
        'occam'          'Nexus 4' \
        'nakasi'         'Nexus 7 (Wi-Fi)' \
        'nakasig'        'Nexus 7 (Mobile)' \
        'takju'          'Galaxy Nexus maguro (with Google Wallet)' \
        'yakju'          'Galaxy Nexus maguro' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $IMAGES
    else
        clear && main
    fi
}
