#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/recovery-data/cm
source $dir/functions/recovery-data/cwm
source $dir/functions/recovery-data/stock
source $dir/functions/recovery-data/twrp

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Install recovery
function recovery {
    eval `resize`
    RECOVERY=$(whiptail \
        --notags \
        --title "Install CWM/TWRP/Stock recovery" \
        --menu "\nWhat recovery would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'cm'        'Cyanogen Recovery' \
        'cwm'       'CWM Recovery' \
        'stock'     'Stock Recovery' \
        'twrp'      'TWRP Recovery' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $RECOVERY
    else
        clear && main
    fi
}
