#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Search devices
function search {
    show_info 'Start the device in fastboot mode...'
    show_warning 'Devices rebooting'
    adb reboot bootloader
    show_info 'Verify that your phone is in fastboot mode...'
    fastboot devices
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "The device is connected." 8 78
    main
}
