#!/bin/bash

function hammerhead-KRT16M {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/hammerhead-krt16m-factory-bd9c39de.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-krt16m
  ./flash-all.sh
  # Timeout
  sleep 5
  # Back
  cd -
  # Cleanup and finish
  rm -rf hammerhead*
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function hammerhead-KTU84P {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/hammerhead-ktu84p-factory-35ea0277.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-ktu84p
  ./flash-all.sh
  # Timeout
  sleep 5
  # Back
  cd -
  # Cleanup and finish
  rm -rf hammerhead*
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function hammerhead-LRX21O {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/hammerhead-lrx21o-factory-01315e08.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-lrx21o
  ./flash-all.sh
  # Timeout
  sleep 5
  # Back
  cd -
  # Cleanup and finish
  rm -rf hammerhead*
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function hammerhead-LMY48M {
  # Download
  show_info 'Download Factory Images...'
  wget https://dl.google.com/dl/android/aosp/hammerhead-lmy48m-factory-bf3c82fd.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-lmy48m
  ./flash-all.sh
  # Timeout
  sleep 5
  # Back
  cd -
  # Cleanup and finish
  rm -rf hammerhead*
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function hammerhead-MRA58N {
  # Download
  show_info 'Download Factory Images...'
  wget https://dl.google.com/dl/android/aosp/hammerhead-mra58n-factory-aeca4139.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-mra58n
  ./flash-all.sh
  # Timeout
  sleep 5
  # Back
  cd -
  # Cleanup and finish
  rm -rf hammerhead*
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function hammerhead-MOB30P {
MOB30P="hammerhead-mob30p-factory-6ceae57a.tgz"
  if [ -f "$MOB30P" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf hammerhead*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-mob30p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/hammerhead-mob30p-factory-6ceae57a.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf hammerhead*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd hammerhead-mob30p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf hammerhead*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus 5
function images-hammerhead {
  eval `resize`
  NEXUS5=$(whiptail \
    --notags \
    --title 'Nexus 5' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    hammerhead-KRT16M 'KitKat 4.4' \
    hammerhead-KTU84P 'KitKat 4.4.4' \
    hammerhead-LRX21O 'Lollipop 5.0' \
    hammerhead-LMY48M 'Lollipop 5.1.1' \
    hammerhead-MRA58N 'Marshmallow 6.0.0' \
    hammerhead-MOB30P 'Marshmallow 6.0.1' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUS5
  else
    clear && main
  fi
}
