#!/bin/bash

function occam-JDQ39 {
JDQ39="occam-jdq39-factory-345dc199.tgz"
  if [ -f "$JDQ39" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-jdq39*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-jdq39
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-jdq39*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/occam-jdq39-factory-345dc199.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-jdq39*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-jdq39
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-jdq39*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function occam-JWR66Y {
JWR66Y="occam-jwr66y-factory-74b1deab.tgz"
  if [ -f "$JWR66Y" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-jwr66y*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-jwr66y
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-jwr66y*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/occam-jwr66y-factory-74b1deab.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-jwr66y*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-jwr66y
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-jwr66y*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function occam-KRT16S {
KRT16S="occam-krt16s-factory-2006f418.tgz"
  if [ -f "$KRT16S" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-krt16s*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-krt16s
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-krt16s*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/occam-krt16s-factory-2006f418.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-krt16s*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-krt16s
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-krt16s*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function occam-KTU84P {
KTU84P="occam-ktu84p-factory-b6ac3ad6.tgz"
  if [ -f "$KTU84P" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-ktu84p*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-ktu84p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-ktu84p*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/occam-ktu84p-factory-b6ac3ad6.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-ktu84p*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-ktu84p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-ktu84p*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function occam-LRX21T {
LRX21T="occam-lrx21t-factory-51cee750.tgz"
  if [ -f "$LRX21T" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-lrx21t*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-lrx21t
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-lrx21t*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/occam-lrx21t-factory-51cee750.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-lrx21t*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-lrx21t
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-lrx21t*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function occam-LMY48T {
LMY48T="occam-lmy48t-factory-416938f1.tgz"
  if [ -f "$LMY48T" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-lmy48t*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-lmy48t
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-lmy48t*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/occam-lmy48t-factory-416938f1.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf occam-lmy48t*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd occam-lmy48t
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf occam-lmy48t*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus 4
function images-occam {
  eval `resize`
  NEXUS4=$(whiptail \
    --notags \
    --title 'Nexus 4' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    occam-JDQ39 'Jelly Bean 4.2.2' \
    occam-JWR66Y 'Jelly Bean 4.3' \
    occam-KRT16S 'KitKat 4.4' \
    occam-KTU84P 'KitKat 4.4.4' \
    occam-LRX21T 'Lollipop 5.0' \
    occam-LMY48T 'Lollipop 5.1.1' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUS4
  else
    clear && main
  fi
}
