#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function angler-MMB29N {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/angler-mmb29n-factory-b1463752.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf angler*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd angler-mmb29n
  ./flash-all.sh
  # Timeout
  sleep 5
  # Cleanup and finish
  rm angler*.tgz
  rm -rf angler*/
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function angler-MHC19Q {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/angler-mhc19q-factory-f5a4e7a1.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf angler*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd angler-mhc19q
  ./flash-all.sh
  # Timeout
  sleep 5
  # Cleanup and finish
  rm angler*.tgz
  rm -rf angler*/
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

# Nexus 6P
function images-angler {
  eval `resize`
  NEXUS6P=$(whiptail \
      --notags \
      --title "Nexus 6P" \
      --menu "\nWhat is the firmware version you want to install?" \
      --ok-button "Install" \
      --cancel-button "Go Back" \
      $LINES $COLUMNS $(( $LINES - 12 )) \
      angler-MMB29N "Marshmallow 6.0.0" \
      angler-MHC19Q "Marshmallow 6.0.1" \
      3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $NEXUS6P
    else
        clear && main
    fi
}
