#!/bin/bash

function fugu-LRX21V {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/fugu-lrx21v-factory-64050f47.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf fugu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd fugu-lrx21v
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function fugu-LMY48N {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/fugu-lmy48n-factory-3b9d8638.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf fugu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd fugu-lmy48n
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function fugu-MRA58N {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/fugu-mra58n-factory-8517d819.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf fugu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd fugu-mra58n
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function fugu-MMB29V {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/fugu-mmb29v-factory-2db4c688.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf fugu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd fugu-mmb29v
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

# Nexus Player
function images-fugu {
  eval `resize`
  NEXUSPLAY=$(whiptail \
      --notags \
      --title "Nexus Player" \
      --menu "\nWhat is the firmware version you want to install?" \
      --ok-button "Install" \
      --cancel-button "Go Back" \
      $LINES $COLUMNS $(( $LINES - 12 )) \
      "fugu-LRX21V"         "Lollipop 5.0" \
      "fugu-LMY48N"         "Lollipop 5.1.1" \
      "fugu-MRA58N"         "Marshmallow 6.0.0" \
      "fugu-MMB29V"         "Marshmallow 6.0.1" \
      3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $NEXUSPLAY
    else
        clear && main
    fi
}
