#!/bin/bash

function fugu-LRX21V {
LRX21V="fugu-lrx21v-factory-64050f47.tgz"
  if [ -f "$LRX21V" ]; then
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-lrx21v-factory-64050f47.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf fugu-lrx21v*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd fugu-lrx21v
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-lrx21v*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-lrx21v-factory-64050f47.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf fugu-lrx21v*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd fugu-lrx21v
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-lrx21v*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function fugu-LMY48N {
LMY48N="fugu-lmy48n-factory-3b9d8638.tgz"
  if [ -f "$LMY48N" ]; then
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-lmy48n-factory-3b9d8638.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf fugu-lmy48n*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd fugu-lmy48n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-lmy48n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-lmy48n-factory-3b9d8638.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf fugu-lmy48n*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd fugu-lmy48n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-lmy48n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function fugu-MRA58N {
MRA58N="fugu-mra58n-factory-8517d819.tgz"
  if [ -f "$MRA58N" ]; then
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-mra58n-factory-8517d819.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf fugu-mra58n*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd fugu-mra58n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-mra58n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-mra58n-factory-8517d819.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf fugu-mra58n*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd fugu-mra58n
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-mra58n*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function fugu-MOB30P {
MOB30P="fugu-mob30p-factory-08696c8b.tgz"
  if [ -f "$MOB30P" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf fugu-mob30p*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd fugu-mob30p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-mob30p*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/fugu-mob30p-factory-08696c8b.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf fugu-mob30p*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd fugu-mob30p
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf fugu-mob30p*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus Player
function images-fugu {
  eval `resize`
  NEXUSPLAY=$(whiptail \
    --notags \
    --title 'Nexus Player' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    fugu-LRX21V 'Lollipop 5.0' \
    fugu-LMY48N 'Lollipop 5.1.1' \
    fugu-MRA58N 'Marshmallow 6.0' \
    fugu-MOB30P 'Marshmallow 6.0.1' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUSPLAY
  else
    clear && main
  fi
}
