#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function shamu-MXB48T {
  # Download
  show_info 'Download Factory Images...'
  curl -O
  show_info 'Extraction Factory Images...'
  tar zxf shamu*.tgz
  show_info 'Install Factory Images...'
  show_warning ' '
  cd shamu-
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

# Nexus 6
function images-shamu {
  eval `resize`
  NEXUS6=$(whiptail \
      --notags \
      --title "Nexus 6" \
      --menu "\nFor what device you want to flash the recovery?" \
      --ok-button "Install" \
      --cancel-button "Go Back" \
      $LINES $COLUMNS $(( $LINES - 12 )) \
      "shamu-LRX21O"
      "shamu-LRX22C"
      "shamu-LMY48Y"
      "shamu-LYZ28N"
      "shamu-LVY48I"
      "shamu-MRA58X"
      "shamu-MMB29V"         "Marshmallow 6.0.1" \
      3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $NEXUS6
    else
        clear && main
    fi
}
