#!/bin/bash

function bullhead-MDB08M {
MDB08M="bullhead-mdb08m-factory-5867cc27.tgz"
  if [ -f "$MDB08M" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf bullhead*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd bullhead-mdb08m
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf bullhead*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download Factory Images...'
    wget https://dl.google.com/dl/android/aosp/bullhead-mdb08m-factory-5867cc27.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf bullhead*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd bullhead-mdb08m
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf bullhead*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

function bullhead-MHC19Q {
MHC19Q="bullhead-mhc19q-factory-22ba5e5a.tgz"
  if [ -f "$MHC19Q" ]; then
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf bullhead*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd bullhead-mhc19q
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf bullhead*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  else
    # Download
    show_info 'Download ...'
    wget https://dl.google.com/dl/android/aosp/bullhead-mhc19q-factory-22ba5e5a.tgz
    # Extract
    show_info 'Extraction Factory Images...'
    tar zxf bullhead*.tgz
    # Install
    show_info 'Install Factory Images...'
    cd bullhead-mhc19q
    ./flash-all.sh
    # Timeout
    sleep 5
    # Back
    cd -
    # Cleanup and finish
    rm -rf bullhead*
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "Installation complete." 8 78
    images
  fi
}

# Nexus 5X
function images-bullhead {
  eval `resize`
  NEXUS5X=$(whiptail \
    --notags \
    --title 'Nexus 5X' \
    --menu '\nWhat is the firmware version you want to install?' \
    --ok-button 'Install' \
    --cancel-button 'Go Back' \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    bullhead-MDB08M 'Marshmallow 6.0.0' \
    bullhead-MHC19Q 'Marshmallow 6.0.1' \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $NEXUS5X
  else
    clear && main
  fi
}
