#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function hammerhead-KRT16M {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/hammerhead-krt16m-factory-bd9c39de.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-krt16m
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function hammerhead-KTU84P {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/hammerhead-ktu84p-factory-35ea0277.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-ktu84p
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function hammerhead-LRX21O {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/hammerhead-lrx21o-factory-01315e08.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-lrx21o
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function hammerhead-LMY48M {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/hammerhead-lmy48m-factory-bf3c82fd.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-lmy48m
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function hammerhead-MRA58N {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/hammerhead-mra58n-factory-aeca4139.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-mra58n
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function hammerhead-MMB29V {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/hammerhead-mmb29v-factory-62a68ee9.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf hammerhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd hammerhead-mmb29v
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

# Nexus 5
function images-hammerhead {
  eval `resize`
  NEXUS5=$(whiptail \
      --notags \
      --title "Nexus 5" \
      --menu "\nFor what device you want to flash the recovery?" \
      --ok-button "Install" \
      --cancel-button "Go Back" \
      $LINES $COLUMNS $(( $LINES - 12 )) \
      "hammerhead-KRT16M"         "KitKat 4.4" \
      "hammerhead-KTU84P"         "KitKat 4.4.4" \
      "hammerhead-LRX21O"         "Lollipop 5.0" \
      "hammerhead-LMY48M"         "Lollipop 5.1.1" \
      "hammerhead-MRA58N"         "Marshmallow 6.0.0" \
      "hammerhead-MMB29V"         "Marshmallow 6.0.1" \
      3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $NEXUS5
    else
        clear && main
    fi
}
