#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function bullhead-MDB08M {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/bullhead-mdb08m-factory-5867cc27.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf bullhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd bullhead-mdb08m
  ./flash-all.sh
  # Timeout
  sleep 5
  # Cleanup and finish
  rm bullhead*.tgz
  rm -rf bullhead*/
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function bullhead-MHC19Q {
  # Download
  show_info 'Download ...'
  curl -O https://dl.google.com/dl/android/aosp/bullhead-mhc19q-factory-22ba5e5a.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf bullhead*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd bullhead-mhc19q
  ./flash-all.sh
  # Timeout
  sleep 5
  # Cleanup and finish
  rm bullhead*.tgz
  rm -rf bullhead*/
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

# Nexus 5X
function images-bullhead {
    eval `resize`
    NEXUS5X=$(whiptail \
        --notags \
        --title "Nexus 5X" \
        --menu "\nWhat is the firmware version you want to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        "bullhead-MDB08M"         "Marshmallow 6.0.0" \
        "bullhead-MHC19Q"         "Marshmallow 6.0.1" \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $NEXUS5X
    else
        clear && main
    fi
}
