#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function shamu-LRX21O {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/shamu-lrx21o-factory-e028f5ea.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf shamu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd shamu-lrx21o
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function shamu-LRX22C {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/shamu-lrx22c-factory-ff173fc6.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf shamu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd shamu-lrx22c
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function shamu-LMY47I {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/shamu-lmy47i-factory-c8afc588.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf shamu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd shamu-lmy47i
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function shamu-LMY48Y {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/shamu-lmy48y-factory-df0504a8.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf shamu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd shamu-lmy48y
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function shamu-MRA58X {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/shamu-mra58x-factory-7ddc0948.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf shamu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd shamu-mra58x
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function shamu-MMB29X {
  # Download
  show_info 'Download Factory Images...'
  curl -O https://dl.google.com/dl/android/aosp/shamu-mmb29x-factory-ef4cbb75.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf shamu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd shamu-mmb29x
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

# Nexus 6
function images-shamu {
  eval `resize`
  NEXUS6=$(whiptail \
      --notags \
      --title "Nexus 6" \
      --menu "\nWhat is the firmware version you want to install?" \
      --ok-button "Install" \
      --cancel-button "Go Back" \
      $LINES $COLUMNS $(( $LINES - 12 )) \
      "shamu-LRX21O"    "Lollipop 5.0.0" \
      "shamu-LRX22C"    "Lollipop 5.0.1" \
      "shamu-LMY47I"    "Lollipop 5.1.0" \
      "shamu-LMY48Y"    "Lollipop 5.1.1" \
      "shamu-MRA58X"    "Marshmallow 6.0.0" \
      "shamu-MMB29X"    "Marshmallow 6.0.1" \
      3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $NEXUS6
    else
        clear && main
    fi
}
