#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/developer-preview-data/developer-preview-ryu
source $dir/functions/developer-preview-data/developer-preview-angler
source $dir/functions/developer-preview-data/developer-preview-bullhead
source $dir/functions/developer-preview-data/developer-preview-shamu
source $dir/functions/developer-preview-data/developer-preview-fugu
source $dir/functions/developer-preview-data/developer-preview-volantisg
source $dir/functions/developer-preview-data/developer-preview-volantis

# Install Factory Images
function developer-preview {
    eval `resize`
    IMAGES=$(whiptail \
        --notags \
        --title "Install Factory Images" \
        --menu "\nWhich device you want to flash?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'developer-preview-ryu'            'Pixel C' \
        'developer-preview-angler'         'Nexus 6P' \
        'developer-preview-bullhead'       'Nexus 5X' \
        'developer-preview-shamu'          'Nexus 6' \
        'developer-preview-fugu'           'Nexus Player' \
        'developer-preview-volantisg'      'Nexus 9 (LTE)' \
        'developer-preview-volantis'       'Nexus 9 (Wi-Fi)' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $IMAGES
    else
        clear && main
    fi
}
