#!/bin/bash

# SuperSU
function root {
  show_info 'Download Latest SuperSU...'
  curl -O https://download.chainfire.eu/921/SuperSU/UPDATE-SuperSU-v2.65-20151226141550.zip?retrieve_file=1
  show_info 'Extraction SuperSU...'
  unzip UPDATE-SuperSU-*.zip
  adb push ./UPDATE-SuperSU-v2.65-20151226141550.zip /sdcard/
  adb reboot-bootloader
  sleep 5
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Recovery Mode Manually install the Root File." 8 78
}
