#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# SuperSU
function root {
  show_info 'Download Latest SuperSU...'
  curl -O https://download.chainfire.eu/921/SuperSU/UPDATE-SuperSU-v2.65-20151226141550.zip?retrieve_file=1
  show_info 'Extraction SuperSU...'
  unzip UPDATE-SuperSU-*.zip
  adb push ./UPDATE-SuperSU-v2.65-20151226141550.zip /sdcard/
  adb reboot-bootloader
  sleep 5
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Recovery Mode Manually install the Root File." 8 78
}
