#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Pixel C
function cm-ryu {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 6P
function cm-angler {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/angler-latest-recovery.img http://download.cyanogenmod.org/get/angler-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery angler*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 5X
function cm-bullhead {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/bullhead-latest-recovery.img http://download.cyanogenmod.org/get/bullhead-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery bullhead*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 6
function cm-shamu {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/shamu-latest-recovery.img http://download.cyanogenmod.org/get/shamu-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery shamu*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus Player
function cm-fugu {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/fugu-latest-recovery.img http://download.cyanogenmod.org/get/fugu-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery fugu*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 9
function cm-flounder {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/flounder-latest-recovery.img http://download.cyanogenmod.org/get/flounder-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery flounder*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 9
function cm-flounder-lte {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/flounder_lte-latest-recovery.img http://download.cyanogenmod.org/get/flounder_lte-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery flounder-lte*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 5
function cm-hammerhead {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/hammerhead-latest-recovery.img http://download.cyanogenmod.org/get/hammerhead-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery hammerhead*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 5 CAF
function cm-hammerheadcaf {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/hammerheadcaf-latest-recovery.img http://download.cyanogenmod.org/get/hammerheadcaf-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery hammerheadcaf*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 7
function cm-flo {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/flo-latest-recovery.img http://download.cyanogenmod.org/get/flo-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery flo*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 7
function cm-deb {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/deb-latest-recovery.img http://download.cyanogenmod.org/get/deb-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery deb*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 10
function cm-manta {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/manta-latest-recovery.img http://download.cyanogenmod.org/get/manta-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery manta*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 4
function cm-mako {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/mako-latest-recovery.img http://download.cyanogenmod.org/get/mako-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery mako*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 7
function cm-grouper {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/grouper-latest-recovery.img http://download.cyanogenmod.org/get/grouper-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery grouper*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 7
function cm-tilapia {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/tilapia-latest-recovery.img http://download.cyanogenmod.org/get/tilapia-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery tilapia*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Galaxy Nexus
function cm-maguro {
  # Download
  show_info 'Download Latest Nightly Recovery...'
  wget --referer=http://download.cyanogenmod.org/get/maguro-latest-recovery.img http://download.cyanogenmod.org/get/maguro-latest-recovery.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery maguro*.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
	rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# TWRP
function cm {
    eval `resize`
    CM=$(whiptail \
        --notags \
        --title "TeamWin - TWRP" \
        --menu "\nFor what device you want to flash the recovery?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        "cm-ryu"            "Pixel C" \
        "cm-angler"         "Nexus 6P" \
        "cm-bullhead"       "Nexus 5X" \
        "cm-shamu"          "Nexus 6" \
        "cm-fugu"           "Nexus Player" \
        "cm-flounder"       "Nexus 9 (Wi-Fi)" \
        "cm-flounder-lte"   "Nexus 9 (Mobile)" \
        "cm-hammerhead"     "Nexus 5" \
        "cm-hammerheadcaf"  "Nexus 5 (CAF)" \
        "cm-flo"            "Nexus 7 [2013] (Wi-Fi)" \
        "cm-deb"            "Nexus 7 [2013] (Mobile)" \
        "cm-manta"          "Nexus 10" \
        "cm-mako"           "Nexus 4" \
        "cm-grouper"        "Nexus 7 (Wi-Fi)" \
        "cm-tilapia"        "Nexus 7 (Mobile)" \
        "cm-maguro"         "Galaxy Nexus (GSM/HSPA+)" \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $CM
    else
        clear && main
    fi
}
