#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function backup-apk {
  show_warning 'Enter your password on your device.'
  adb backup -apk -obb -shared -all -system -f ./backup-data/Android_System_$(date +%F-%H-%M).ab
}

function restore-apk {
  cd ./backup-data
  ls
  show_warning 'Enter your password on your device.'
  adb restore ./backup-data/Android_System_$(date +%F-%H-%M).ab
}

function backup-all {
  adb shell
  su
  show_warning 'Enter your password on your device.'
  dd if=/dev/block/mmcblk0p17 of=/sdcard/data.ext4
  dd if=/dev/block/mmcblk0p16 of=/sdcard/cache.ext4
  dd if=/dev/block/mmcblk0p27 of=/sdcard/efs.img
  dd if=/dev/block/mmcblk0p15 of=/sdcard/system.ext4
  dd if=/dev/block/mmcblk0p8 of=/sdcard/boot.img
  dd if=/dev/block/mmcblk0p13 of=/sdcard/recovery.img
  exit
  exit
}

function restore-all {
  adb shell
  su
  show_warning 'Enter your password on your device.'
  dd if=/sdcard/data.ext4 of=/dev/block/mmcblk0p17
  dd if=/sdcard/cache.ext4 of=/dev/block/mmcblk0p16
  dd if=/sdcard/efs.img of=/dev/block/mmcblk0p27
  dd if=/sdcard/system.ext4 of=/dev/block/mmcblk0p15
  dd if=/sdcard/boot.img of=/dev/block/mmcblk0p8
  dd if=/sdcard/recovery.img of /dev/block/mmcblk0p13
  exit
  exit
}

# Backup/Restore
function backup {
    eval `resize`
    BACKUP=$(whiptail \
        --notags \
        --title "Backup/Restore" \
        --menu "\nWhat recovery would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'backup-apk'        ' ' \
        'restore-apk'       ' ' \
        'mount'             ' ' \
        'unmount'           ' ' \
        'backup-all'        ' ' \
        'restore-all'       ' ' \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $BACKUP
    else
        clear && main
    fi
}
