#!/bin/bash

# 
function root {
  show_info 'Download Latest ...'
  
  show_info 'Extraction ...'
  unzip *.zip
  adb push ./.zip /sdcard/
  adb reboot-bootloader
  sleep 5
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Recovery Mode Manually install the Root File." 8 78
}
