#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function fugu-dp1 {
  # Download
  show_info 'Download Factory Images...'
  curl -O http://storage.googleapis.com/androiddevelopers/shareables/preview/fugu-npc56r-preview-7027d5b6.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf fugu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd fugu-npc56w
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

function fugu-dp2 {
  # Download
  show_info 'Download Factory Images...'
  curl -O http://storage.googleapis.com/androiddevelopers/shareables/preview/fugu-npc91o-factory-3b8e3f56.tgz
  # Extract
  show_info 'Extraction Factory Images...'
  tar zxf fugu*.tgz
  # Install
  show_info 'Install Factory Images...'
  cd fugu-npc91o
  ./flash-all.sh
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  images
}

# Nexus Player
function developer-preview-fugu {
  eval `resize`
  NEXUSPLAYER=$(whiptail \
      --notags \
      --title "Nexus Player" \
      --menu "\nWhat is the firmware version you want to install?" \
      --ok-button "Install" \
      --cancel-button "Go Back" \
      $LINES $COLUMNS $(( $LINES - 12 )) \
      "fugu-dp1"         "Developer Preview 1" \
      "fugu-dp2"         "Developer Preview 2" \
      3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $NEXUSPLAYER
    else
        clear && main
    fi
}
