#!/bin/bash

# Authors:
#   Igor Dyatlov <dyatlov.igor@gmail.com>
#
# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function twrp-ryu {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# Nexus 6P
function twrp-angler {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/angler/twrp-3.0.2-0-angler.img.html https://dl.twrp.me/angler/twrp-3.0.2-0-angler.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.0.0-0-angler.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-bullhead {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/bullhead/twrp-3.0.2-0-bullhead.img.html https://dl.twrp.me/bullhead/twrp-3.0.2-0-bullhead.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.0.0-0-bullhead.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-shamu {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/shamu/twrp-3.0.2-0-shamu.img.html https://dl.twrp.me/shamu/twrp-3.0.2-0-shamu.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.0.0-0-shamu.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-fugu {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/fugu/twrp-3.0.0-0-fugu.img.html https://dl.twrp.me/fugu/twrp-3.0.0-0-fugu.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.0.0-0-fugu.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-flounder {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/flounder/twrp-3.0.0-2-flounder.img.html https://dl.twrp.me/flounder/twrp-3.0.0-2-flounder.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.0.0-2-flounder.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-hammerhead {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/hammerhead/twrp-3.2.1-1-hammerhead.img.html https://dl.twrp.me/hammerhead/twrp-3.2.1-1-hammerhead.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.2.1-1-hammerhead.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm twrp-3.2.1-1-hammerhead.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-hammerheadcaf {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/hammerheadcaf/twrp-3.1.0-0-hammerheadcaf.img.html https://dl.twrp.me/hammerheadcaf/twrp-3.1.0-0-hammerheadcaf.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.1.0-0-hammerheadcaf.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm twrp-3.1.0-0-hammerheadcaf.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-flo {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/flo/twrp-3.2.1-0-flo.img.html https://dl.twrp.me/flo/twrp-3.2.1-0-flo.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.2.1-0-flo.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm twrp-3.2.1-0-flo.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-deb {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/deb/twrp-3.0.0-0-deb.img.html https://dl.twrp.me/deb/twrp-3.0.0-0-deb.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.0.0-0-deb.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-manta {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/manta/twrp-3.0.0-1-manta.img.html https://dl.twrp.me/manta/twrp-3.0.0-1-manta.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.0.0-1-manta.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-mako {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/mako/twrp-3.0.2-0-mako.img.html https://dl.twrp.me/mako/twrp-3.0.2-0-mako.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.0.0-0-mako.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-grouper {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/grouper/twrp-3.0.0-0-grouper.img.html https://dl.twrp.me/grouper/twrp-3.0.0-0-grouper.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.0.0-0-grouper.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-tilapia {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/tilapia/twrp-2.8.7.0-tilapia.img.html https://dl.twrp.me/tilapia/twrp-2.8.7.0-tilapia.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-2.8.7.0-tilapia.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-maguro {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/maguro/twrp-3.2.1-0-maguro.img.html https://dl.twrp.me/maguro/twrp-3.2.1-0-maguro.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.2.1-0-maguro.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm twrp-3.2.1-0-maguro.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-toroplus {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/toroplus/twrp-3.1.1-0-toroplus.img.html https://dl.twrp.me/toroplus/twrp-3.1.1-0-toroplus.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.1.1-0-toroplus.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

function twrp-toro {
  # Download
  show_info 'Download the latest TWRP image...'
  wget --referer=https://dl.twrp.me/toro/twrp-3.1.1-0-toro.img.html https://dl.twrp.me/toro/twrp-3.1.1-0-toro.img
  # Erasing old recovery
  show_warning 'Erasing old recovery...'
  fastboot erase recovery
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  show_info 'Flashing recovery...'
  fastboot flash recovery twrp-3.1.1-0-toro.img
  show_success 'Done.'
  # Reboot bootloader
  show_warning 'Devices rebooting'
  fastboot reboot-bootloader
  # Timeout
  sleep 5
  # Cleanup and finish
  rm *.img
  # Done
  show_success 'Done.'
  whiptail --title "Finished" --msgbox "Installation complete." 8 78
  recovery
}

# TWRP
function twrp {
  eval `resize`
  TWRP=$(whiptail \
    --notags \
    --title "TeamWin - TWRP" \
    --menu "\nFor what device you want to flash the recovery?" \
    --ok-button "Install" \
    --cancel-button "Go Back" \
  $LINES $COLUMNS $(( $LINES - 12 )) \
    twrp-ryu "Pixel C" \
    twrp-angler "Nexus 6P" \
    twrp-bullhead "Nexus 5X" \
    twrp-shamu "Nexus 6" \
    twrp-fugu "Nexus Player" \
    twrp-flounder "Nexus 9" \
    twrp-hammerhead "Nexus 5" \
    twrp-hammerheadcaf "Nexus 5 (CAF)" \
    twrp-flo "Nexus 7 [2013] (Wi-Fi)" \
    twrp-deb "Nexus 7 [2013] (Mobile)" \
    twrp-manta "Nexus 10" \
    twrp-mako "Nexus 4" \
    twrp-grouper "Nexus 7 (Wi-Fi)" \
    twrp-tilapia "Nexus 7 (Mobile)" \
    twrp-maguro "Galaxy Nexus (GSM/HSPA+)" \
    twrp-toroplus "Galaxy Nexus (Sprint)" \
    twrp-toro "Galaxy Nexus (Verizon)" \
  3>&1 1>&2 2>&3)

exitstatus=$?
  if [ $exitstatus = 0 ]; then
    clear && $TWRP
  else
    clear && main
  fi
}
